### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by FlowerWrong** [m0khi/libUTtuntap#1]
Hi! There is no OSX support.

**Comment by mmokhi** [comment]
Hi.
Thanks for your feedback :-)
OSX's tun/tap drivers are sooo similar to FreeBSD's.
It'll be gonna ready soooon ;-)

Best regards,

**Comment by FlowerWrong** [comment]
OSX now support named utun. See https://github.com/mafintosh/utun/blob/master/utun.cc#L25
